version: "3.7"

services:
    linkset_creation:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - S3_BUCKET
            - S3_REGION
            - S3_PATH=${S3_LINKSET_PATH}
            - S3_SOURCE_DATA_PATH
            - OBJECT_DATASET_URI=${GEOFABRIC_DATASET_URI}
