version: "3.4"

services:
  linksets:
    command: /bin/sh -c 'curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o ./wait-for-it.sh && chmod +x ./wait-for-it.sh && ./wait-for-it.sh postgis:5432 && cd /app/mb2cc && python linksets_mb_cc_builder.py && python linksets_mb_cc_triples_builder.py && python upload_mbcc_ttl.py'
