version: "3.4"

services:
  linksets:
    build:
      context: .
      target: python-specific
    env_file:
      - ../../../common/common.env
      - .env
    environment:
      - S3_BUCKET
      - S3_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    volumes:
      - .:/app
    links:
      - postgis
    depends_on:
      - postgis

  postgis:
    image: mdillon/postgis:11
    shm_size: 8g
    ports:
      - 5437:5432
