version: "3.7"

services:
    asgs_harvest:
        build:
            context: .
            dockerfile: Dockerfile
        environment: 
            - AWS_ACCESS_KEY_ID=${LOCI_S3_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${LOCI_S3_SECRET_ACCESS_KEY}
